apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "document-engine.fullname" . }}-config
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
{{- with .Values.config.replaceSecretsFromEnv }}
  REPLACE_SECRETS_FROM_ENV: {{ . | quote }}
{{- end }}
  PSPDFKIT_WORKER_POOL_SIZE: {{ .Values.config.workerPoolSize | quote }}
  PORT: {{ .Values.config.port | quote }}
  SERVER_REQUEST_TIMEOUT: {{ mul 1000 .Values.config.requestTimeoutSeconds | quote }}
  PSPDFKIT_WORKER_TIMEOUT: {{ mul 1000 .Values.config.workerTimeoutSeconds | quote }}
  PDF_GENERATION_TIMEOUT: {{ mul 1000 .Values.config.generationTimeoutSeconds | quote }}
  REMOTE_URL_FETCH_TIMEOUT: {{ mul 1000 .Values.config.urlFetchTimeoutSeconds | quote }}
  READ_ANNOTATION_BATCH_TIMEOUT: {{ mul 1000 .Values.config.readAnnotationBatchTimeoutSeconds | quote }}
  MAX_UPLOAD_SIZE_BYTES: {{ mul 1048576 .Values.config.maxUploadSizeMegaBytes | quote }}
  ASYNC_JOBS_TTL: {{ .Values.config.asyncJobsTtlSeconds | quote }}
  ALLOW_DOCUMENT_UPLOADS: {{ .Values.config.allowDocumentUploads | quote }}
  ALLOW_REMOTE_DOCUMENTS: {{ .Values.config.allowRemoteDocuments | quote }}
  ALLOW_DOCUMENT_GENERATION: {{ .Values.config.allowDocumentGeneration | quote }}
  ALLOW_REMOTE_ASSETS_IN_GENERATION: {{ .Values.config.allowRemoteAssetsInGeneration | quote }}
  IGNORE_INVALID_ANNOTATIONS: {{ .Values.config.ignoreInvalidAnnotations | quote }}
  AUTOMATIC_LINK_EXTRACTION: {{ .Values.config.automaticLinkExtraction | quote }}
  MIN_SEARCH_QUERY_LENGTH: {{ .Values.config.minSearchQueryLength | quote }}
{{- with .Values.config.proxy.http }}
  HTTP_PROXY: {{ . | quote }}
{{- end }}
{{- with .Values.config.proxy.https }}
  HTTPS_PROXY: {{ . | quote }}
{{- end }}
{{- with .Values.config.trustedProxies }}
  TRUSTED_PROXIES: {{ . | quote }}
{{- end }}
{{- with .Values.certificateTrust.downloaderTrustFileName }}
  DOWNLOADER_CERT_FILE_PATH: "/certificate-stores-custom/{{ . }}"
{{- end }}
{{- with .Values.documentSigningService }}
{{-   if .enabled }}
  SIGNING_SERVICE_URL: {{ .url | quote }}
  SIGNING_SERVICE_TIMEOUT:  {{ mul 1000 .timeoutSeconds | quote }}
  DEFAULT_SIGNER_NAME: {{ default "none" .defaultSignerName | quote }}
  DEFAULT_SIGNATURE_REASON: {{ default "none" .defaultSignatureReason | quote }}
  DEFAULT_SIGNATURE_LOCATION: {{ default "none" .defaultSignatureLocation | quote }}
  DIGITAL_SIGNATURE_HASH_ALGORITHM: {{ .digitalSignatureHashAlgorithm | quote }}
  DIGITAL_SIGNATURE_CADES_LEVEL: {{ .digitalSignatureCadesLevel | quote }}
  DIGITAL_SIGNATURE_CERTIFICATE_CHECK_TIME: {{ default "current_time" .digitalSignatureCertificateCheckTime | quote }}
  TIMESTAMP_AUTHORITY_URL: {{ .timestampAuthority.url | quote }}
  TIMESTAMP_AUTHORITY_USERNAME: {{ .timestampAuthority.username | quote }}
  TIMESTAMP_AUTHORITY_PASSWORD: {{ .timestampAuthority.password | quote }}
{{-   end }}
{{- end }}
{{- with .Values.observability }}
{{-   if and .metrics.enabled .metrics.statsd.enabled }}
{{-     with .metrics.statsd }}
  STATSD_HOST: {{ .host | quote }}
  STATSD_PORT: {{ .port | quote }}
  STATSD_CUSTOM_TAGS: {{ tpl .customTags $ | quote }}
{{-     end }}
{{-   end }}
  LOG_LEVEL: {{ .log.level | quote }}
  HEALTHCHECK_LOGLEVEL: {{ .log.healthcheckLevel | quote }}
{{-   with .opentelemetry }}
{{-     if .enabled }}
  ENABLE_OPENTELEMETRY: "true"
{{-       with .otlpExporterEndpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ . | quote }}
{{-       end }}
{{-       with .otlpExporterProtocol }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ . | quote }}
{{-       end }}
{{-       with .otelServiceName }}
  OTEL_SERVICE_NAME: {{ . | quote }}
{{-       end }}
{{-       with .otelResourceAttributes }}
  OTEL_RESOURCE_ATTRIBUTES: {{ . | quote }}
{{-       end }}
{{-       with .otelPropagators }}
  OTEL_PROPAGATORS: {{ . | quote }}
{{-       end }}
{{-       with .otelTracesSampler }}
  OTEL_TRACES_SAMPLER: {{ . | quote }}
{{-       end }}
{{-       with .otelTracesSamplerArg }}
  OTEL_TRACES_SAMPLER_ARG: {{ . | quote }}
{{-       end }}
{{-     else }}
  ENABLE_OPENTELEMETRY: "false"
{{-     end }}
{{-   end }}
{{- end }}
# Can be used for hash updating
  HELM_CHART_VERSION: {{ include "document-engine.chart" . | quote }}
