{{- if (eq (include "document-engine.storage.redis.createSecret" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.fullname" . }}-redis
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
{{- with .Values.pspdfkit.storage.redis }}
{{-     if .sentinels.enabled }}
  REDIS_SENTINELS: {{ .sentinels.urls | join ";" | b64enc | quote }}
  REDIS_SENTINELS_GROUP: {{ .sentinels.group | b64enc | quote }}
{{-     else }}
  REDIS_HOST: {{ .host | b64enc | quote }}
  REDIS_PORT: {{ .port | toString | b64enc | quote }}
  REDIS_SSL: {{ .tls.enabled | toString | b64enc | quote }}
{{-     end }}
  REDIS_DATABASE: {{ .database | b64enc | quote }}
  REDIS_USERNAME: {{ .username | b64enc | quote }}
  REDIS_PASSWORD: {{ .password | b64enc | quote }}
{{- end }}
{{- end }}
