{{- if (eq (include "document-engine.storage.postgres.createSecret" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.fullname" . }}-db-postgres
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
# Normal use
  PGUSER: {{ default "none" .Values.pspdfkit.storage.postgres.username | b64enc | quote }}
  PGPASSWORD: {{ default "none" .Values.pspdfkit.storage.postgres.password | b64enc | quote }}
# Server parameters
  PGHOST: {{ .Values.pspdfkit.storage.postgres.host | b64enc | quote }}
  PGPORT: {{ .Values.pspdfkit.storage.postgres.port | toString | b64enc | quote }}
{{- if .Values.pspdfkit.storage.postgres.tls.enabled }}
  PGSSL: {{ "true" | b64enc | quote }}
{{- else }}
  PGSSL: {{ "false" | b64enc | quote }}
{{- end }}
  PGDATABASE: {{ .Values.pspdfkit.storage.postgres.database | b64enc | quote }}
{{- end }}
