{{- if (eq (include "document-engine.storage.postgres.createAdminSecret" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.fullname" . }}-db-postgres-admin
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
# Administrative access for migrations
  PG_ADMIN_USER: {{ default "postgres" .Values.pspdfkit.storage.postgres.adminUsername | b64enc | quote }}
  PG_ADMIN_PASSWORD: {{ default "none" .Values.pspdfkit.storage.postgres.adminPassword  | b64enc | quote }}
{{- end }}
