{{- if (eq (include "document-engine.storage.s3.createSecret" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.storage.s3.secret.name" . }}
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
{{- with .Values.assetStorage }}
{{-   if and .s3.accessKeyId .s3.secretAccessKey }}
  ASSET_STORAGE_S3_ACCESS_KEY_ID: {{ .s3.accessKeyId | b64enc | quote }}
  ASSET_STORAGE_S3_SECRET_ACCESS_KEY: {{ .s3.secretAccessKey | b64enc | quote }}
{{-   end }}
{{- end }}
{{- end }}
