{{- if (eq (include "document-engine.storage.redis.createSecret" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.fullname" . }}-redis
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
{{- with .Values.config.storage.redis }}
{{-   if .sentinel.enabled }}
  REDIS_SENTINELS: {{ .sentinel.urls | join ";" | b64enc | quote }}
  REDIS_SENTINELS_GROUP: {{ .sentinel.group | b64enc | quote }}
{{-   else }}
  REDIS_HOST: {{ .host | b64enc | quote }}
  REDIS_SSL: {{ .tls.enabled | toString | b64enc | quote }}
{{-   end }}
  REDIS_PORT: {{ .port | toString | b64enc | quote }}
{{-   with .database }}
  REDIS_DATABASE: {{ . | b64enc | quote }}
{{-   end }}
{{-   with .username }}
  REDIS_USERNAME: {{ . | b64enc | quote }}
{{-   end }}
{{-   with .password }}
  REDIS_PASSWORD: {{ . | b64enc | quote }}
{{-   end }}
{{- end }}
{{- end }}
