{{- if not .Values.pspdfkit.auth.api.externalSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.api.secret.name" . }}
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
  API_AUTH_TOKEN: {{ default (randAlphaNum 64) .Values.pspdfkit.auth.api.apiToken | b64enc | quote }}
{{-   if .Values.pspdfkit.auth.api.jwt.enabled }}
  JWT_PUBLIC_KEY: {{ default "none" .Values.pspdfkit.auth.api.jwt.publicKey | b64enc | quote }}
  JWT_ALGORITHM: {{ default "none" .Values.pspdfkit.auth.api.jwt.algorithm | b64enc | quote }}
{{-   end }}
{{- end }}
