apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "document-engine.fullname" . }}-config
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.pspdfkit.log.level | quote }}
  PORT: {{ .Values.service.port | quote }}
  PDF_GENERATION_TIMEOUT: {{ mul 1000 .Values.pspdfkit.generationTimeoutSeconds | quote }}
  SERVER_REQUEST_TIMEOUT: {{ mul 1000 .Values.pspdfkit.requestTimeoutSeconds | quote }}
  REMOTE_URL_FETCH_TIMEOUT: {{ mul 1000 .Values.pspdfkit.urlFetchTimeoutSeconds | quote }}
  READ_ANNOTATION_BATCH_TIMEOUT: {{ mul 1000 .Values.pspdfkit.readAnnotationBatchTimeoutSeconds | quote }}
  MAX_UPLOAD_SIZE_BYTES: {{ mul 1048576 .Values.pspdfkit.maxUploadSizeMegaBytes | quote }}
  PSPDFKIT_WORKER_POOL_SIZE: {{ .Values.pspdfkit.workerPoolSize | quote }}
  ALLOW_DOCUMENT_UPLOADS: {{ .Values.pspdfkit.allowDocumentUploads | quote }}
  ALLOW_REMOTE_DOCUMENTS: {{ .Values.pspdfkit.allowRemoteDocuments | quote }}
  ALLOW_DOCUMENT_GENERATION: {{ .Values.pspdfkit.allowDocumentGeneration | quote }}
  ALLOW_REMOTE_ASSETS_IN_GENERATION: {{ .Values.pspdfkit.allowRemoteAssetsInGeneration | quote }}
  IGNORE_INVALID_ANNOTATIONS: {{ .Values.pspdfkit.ignoreInvalidAnnotations | quote }}
  ASSET_STORAGE_CACHE_SIZE: {{ mul 1048576 .Values.pspdfkit.assetStorageCacheSizeMegaBytes | quote }}
  AUTOMATIC_LINK_EXTRACTION: {{ .Values.pspdfkit.automaticLinkExtraction | quote }}
  MIN_SEARCH_QUERY_LENGTH: {{ .Values.pspdfkit.minSearchQueryLength | quote }}
  DATABASE_CONNECTIONS: {{ .Values.pspdfkit.storage.databaseConnections | quote }}
{{- if .Values.pspdfkit.storage.enableMigrationJobs }}
  ENABLE_DATABASE_MIGRATIONS: "false"
  EXIT_AFTER_DATABASE_MIGRATIONS: "false"
{{- else }}
  ENABLE_DATABASE_MIGRATIONS: "true"
  EXIT_AFTER_DATABASE_MIGRATIONS: "false"
{{- end }}
{{- with .Values.pspdfkit.storage }}
  ASSET_STORAGE_BACKEND: {{ default "built-in" .assetStorageBackend | quote }}
{{- if .enableAssetStorageFallback }}
  ENABLE_ASSET_STORAGE_FALLBACK: "false"
  ENABLE_ASSET_STORAGE_FALLBACK_POSTGRES: "false"
  ENABLE_ASSET_STORAGE_FALLBACK_S3: "false"
  ENABLE_ASSET_STORAGE_FALLBACK_AZURE: "false"
{{- else }}
  ENABLE_ASSET_STORAGE_FALLBACK: {{ .enableAssetStorageFallback | quote }}
  ENABLE_ASSET_STORAGE_FALLBACK_POSTGRES: {{ .enableAssetStorageFallbackPostgres | quote }}
  ENABLE_ASSET_STORAGE_FALLBACK_S3: {{ .enableAssetStorageFallbackS3 | quote }}
  ENABLE_ASSET_STORAGE_FALLBACK_AZURE: {{ .enableAssetStorageFallbackAzure | quote }}
{{- end }}
  USE_REDIS_CACHE: {{ .redis.enabled | quote }}
  USE_REDIS_TTL_FOR_PRERENDERING: {{ .redis.useTtlForPrerendering | quote }}
  REDIS_TTL: {{ .redis.ttlSeconds | int | quote }}
{{- end }}
{{- with .Values.pspdfkit.signingService }}
{{-   if .enabled }}
  SIGNING_SERVICE_URL: {{ .url | quote }}
  SIGNING_SERVICE_TIMEOUT:  {{ mul 1000 .timeoutSeconds | quote }}
  DEFAULT_SIGNER_NAME: {{ default "none" .defaultSignerName | quote }}
  DEFAULT_SIGNATURE_REASON: {{ default "none" .defaultSignatureReason | quote }}
  DEFAULT_SIGNATURE_LOCATION: {{ default "none" .defaultSignatureLocation | quote }}
  DIGITAL_SIGNATURE_HASH_ALGORITHM: {{ .digitalSignatureHashAlgorithm | quote }}
  DIGITAL_SIGNATURE_CADES_LEVEL: {{ .digitalSignatureCadesLevel | quote }}
  DIGITAL_SIGNATURE_CERTIFICATE_CHECK_TIME: {{ default "current_time" .digitalSignatureCertificateCheckTime | quote }}
  TIMESTAMP_AUTHORITY_URL: {{ .timestampAuthority.url | quote }}
  TIMESTAMP_AUTHORITY_USERNAME: {{ .timestampAuthority.username | quote }}
  TIMESTAMP_AUTHORITY_PASSWORD: {{ .timestampAuthority.password | quote }}
{{-   end }}
{{- end }}
{{- with .Values.pspdfkit.trustedProxies }}
  TRUSTED_PROXIES: {{ . | quote }}
{{- end }}
{{- if .Values.prometheusExporter.enabled }}
  STATSD_HOST: localhost
  STATSD_PORT: {{ .Values.prometheusExporter.statsdPort | quote }}
  STATSD_CUSTOM_TAGS: "namespace={{ .Release.Namespace }},app={{ include "document-engine.fullname" . }}"
{{- end }}
{{- with .Values.pspdfkit.observability.opentelemetry }}
{{-   if .enabled }}
  ENABLE_OPENTELEMETRY: "true"
{{-     with .otlpExporterEndpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ . | quote }}
{{-     end }}
{{-     with .otlpExporterProtocol }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ . | quote }}
{{-     end }}
{{-     with .otelServiceName }}
  OTEL_SERVICE_NAME: {{ . | quote }}
{{-     end }}
{{-     with .otelResourceAttributes }}
  OTEL_RESOURCE_ATTRIBUTES: {{ . | quote }}
{{-     end }}
{{-   else }}
  ENABLE_OPENTELEMETRY: "false"
{{-   end }}
{{- end }}
# Can be used for hash updating
  VERSION: {{ include "document-engine.chart" . | quote }}
