{{- if not .Values.pspdfkit.secretKeyBase.externalSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.secretKeyBase.secret.name" . }}
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace ( include "document-engine.secretKeyBase.secret.name" . ) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKeyBase := (get $secretData "SECRET_KEY_BASE") | default ( default (randAlphaNum 256) .Values.pspdfkit.secretKeyBase.value | b64enc) }}
  SECRET_KEY_BASE: {{ $secretKeyBase | quote }}
{{- end }}
