{{- if (eq (include "document-engine.storage.azure.createSecret" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.storage.azure.secret.name" . }}
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
{{- with .Values.assetStorage }}
{{-     if .azure.connectionString }}
  AZURE_STORAGE_ACCOUNT_CONNECTION_STRING: {{ .azure.connectionString | b64enc | quote }}
{{-     else if and .azure.accountName .azure.accountKey }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ .azure.accountName | b64enc | quote }}
  AZURE_STORAGE_ACCOUNT_KEY: {{ .azure.accountKey | b64enc | quote }}
{{-     end }}
{{- end }}
{{- end }}
