{{- if (eq (include "document-engine.storage.redis.createSecret" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.fullname" . }}-redis
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
{{- with .Values.assetStorage.redis }}
{{-   with .username }}
  REDIS_USERNAME: {{ . | b64enc | quote }}
{{-   end }}
{{-   with .password }}
  REDIS_PASSWORD: {{ . | b64enc | quote }}
{{-   end }}
{{- end }}
{{- end }}
