apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "document-engine.fullname" . }}-storage
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
{{- with .Values.assetStorage }}
  ASSET_STORAGE_CACHE_SIZE: {{ mul 1048576 .localCacheSizeMegabytes | quote }}
  ASSET_STORAGE_BACKEND: {{ .backendType | quote }}
{{-   if $.Values.database.enabled }}
{{-     if .backendFallback.enabled }}
  ENABLE_ASSET_STORAGE_FALLBACK: "true"
  ENABLE_ASSET_STORAGE_FALLBACK_POSTGRES: {{ .backendFallback.enabledPostgres | quote }}
  ENABLE_ASSET_STORAGE_FALLBACK_S3: {{ .backendFallback.enabledS3 | quote }}
  ENABLE_ASSET_STORAGE_FALLBACK_AZURE: {{ .backendFallback.enabledAzure | quote }}
{{-     else }}
  ENABLE_ASSET_STORAGE_FALLBACK: "false"
  ENABLE_ASSET_STORAGE_FALLBACK_POSTGRES: "false"
  ENABLE_ASSET_STORAGE_FALLBACK_S3: "false"
  ENABLE_ASSET_STORAGE_FALLBACK_AZURE: "false"
{{-     end }}
{{-     if .s3.bucket }}
  ASSET_STORAGE_S3_BUCKET: {{ .s3.bucket | quote }}
  ASSET_STORAGE_S3_REGION: {{ .s3.region | quote }}
{{-       if .s3.host }}
  ASSET_STORAGE_S3_HOST: {{ .s3.host | quote }}
  ASSET_STORAGE_S3_PORT: {{ .s3.port | quote }}
  ASSET_STORAGE_S3_SCHEME: {{ .s3.scheme | quote }}
{{-       end }}
{{-     end }}
{{-     if .azure.container }}
  AZURE_STORAGE_DEFAULT_CONTAINER: {{ .azure.container | quote }}
{{-       if .azure.apiUrl }}
  AZURE_STORAGE_API_URL: {{ .azure.apiUrl | quote }}
{{-       end }}
{{-     end }}
{{-     if .redis.enabled }}
  USE_REDIS_CACHE: "true"
{{-       with .redis }}
  USE_REDIS_TTL_FOR_PRERENDERING: {{ .useTtlForPrerendering | quote }}
  REDIS_TTL: {{ .ttlSeconds | int | quote }}
{{-         if .sentinel.enabled }}
  REDIS_SENTINELS: {{ .sentinel.urls | join ";" | quote }}
  REDIS_SENTINELS_GROUP: {{ .sentinel.group | quote }}
{{-         else }}
  REDIS_HOST: {{ .host | quote }}
  REDIS_SSL: {{ .tls.enabled | toString | quote }}
{{-         end }}
  REDIS_PORT: {{ .port | toString | quote }}
{{-         with .database }}
  REDIS_DATABASE: {{ . | quote }}
{{-         end }}
{{-       end }}
{{-     else }}
  USE_REDIS_CACHE: "false"
{{-     end }}
{{-   end }}
{{- end }}
# Can be used for hash updating
  HELM_CHART_VERSION: {{ include "document-engine.chart" . | quote }}
