{{- if not .Values.pspdfkit.license.externalSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.fullname" . }}-license
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
  {{- with .Values.pspdfkit.license.activationKey }}
  {{- if not $.Values.pspdfkit.license.isOffline }}
  ACTIVATION_KEY: {{ . | b64enc | quote }}
  {{- else }}
  LICENSE_KEY: {{ . | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
