{{- if and 
       (not .Values.documentEngineLicense.externalSecret.name)
       (eq (include  "document-engine.license.available" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-engine.fullname" . }}-license
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
data:
  {{- with .Values.documentEngineLicense.activationKey }}
  ACTIVATION_KEY: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
