{{- if (eq (include "document-engine.clustering.service.enabled" . ) "true" ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-engine.clustering.service.name" . }}
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.clustering.epmd.port }}
      name: epmd
  selector:
    {{- include "document-engine.selectorLabels" . | nindent 4 }}
{{- end }}
