{{- if (eq (include "document-engine.storage.cleanupJob.enabled" . ) "true" ) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "document-engine.fullname" . }}-db-cleanup
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.documentLifecycle.cleanupJob.schedule }}
  startingDeadlineSeconds: 600
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 1800
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.documentLifecycle.cleanupJob.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
          {{- include "document-engine.cleanupSelectorLabels" . | nindent 12 }}
          {{- with .Values.documentLifecycle.cleanupJob.podLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "document-engine.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- if .Values.initContainers }}
          initContainers:
            {{ toYaml .Values.initContainers | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              envFrom:
                - configMapRef:
                    name: {{ include "document-engine.fullname" . }}
                - secretRef:
                    name: {{ include "document-engine.fullname" . }}
              {{- if .Values.database.postgres.externalSecretName  }}
                - secretRef:
                    name: {{ .Values.database.postgres.externalSecretName }}
              {{- end }}
              {{- if and .Values.database.migrationJob.enabled
                         .Values.database.postgres.externalAdminSecretName  }}
                - secretRef:
                    name: {{ .Values.database.postgres.externalAdminSecretName }}
              {{- end }}
              {{- with .Values.extraEnvFrom }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.extraEnvs }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /document-engine-cleanup/run.sh
              resources:
                {{- toYaml .Values.documentLifecycle.cleanupJob.resources | nindent 16 }}
              volumeMounts:
                - name: cleanup-assets
                  mountPath: /document-engine-cleanup
              {{- if .Values.extraVolumeMounts }}
                {{- toYaml .Values.extraVolumeMounts | nindent 16 }}
              {{- end }}
          {{- if .Values.sidecars }}
            {{ toYaml .Values.sidecars | nindent 12 }}
          {{- end }}
          volumes:
            - name: cleanup-assets
              configMap:
                name: {{ include "document-engine.fullname" . }}-db-cleanup
                defaultMode: 0755
          {{- with .Values.extraVolumes }}
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
