apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: something
  labels: 
    some-label: some-value
  annotations:
    kustomize.toolkit.fluxcd.io/prune: "disabled"
    helm.sh/resource-policy: keep
spec:
  acme:
    server: https://dv.acme-v02.api.pki.goog/directory
    email: me@example.com

    privateKeySecretRef:
      name: google-cluster-issuer

    externalAccountBinding:
      keyID: my-key-id
      keySecretRef:
        name: google-eab-secret
        key: eab_hmac

    solvers:
      - selector: 
          dnsZones:
            - "services.example.com"
        dns01:
          route53:
            region: eu-west-1
