documentEngineLicense:
  activationKey: ""
  externalSecret: 
    name: ""
    key: DOCUMENT_ENGINE_ACTIVATION_KEY

apiAuth:
  apiToken: secret

config:
  trustedProxies: default

documentSigningService:
  enabled: true
  url: http://signing-service:6000/sign
  timeoutSeconds: 10

database: 
  enabled: true
  engine: postgres
  migrationJob:
    enabled: false
  postgres:
    enabled: true
    host: document-engine-postgresql
    database: document-engine
    tls:
      enabled: false
    auth: 
      username: postgres
      password: postgres
      adminUsername: postgres
      adminPassword: postgres

assetStorage:
  backendType: built-in
  backendFallback:
    enabled: false

dashboard:
  auth:
    username: admin
    password: admin

observability:
  log:
    level: debug
  opentelemetry:
    enabled: false

replicaCount: 1

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

resources:
  limits:
    cpu: "4"
    memory: 8Gi
  requests:
    cpu: "1"
    memory: 1Gi

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "4 16k"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
  hosts:
    - paths:
        - path: /
          pathType: ImplementationSpecific

postgresql:
  enabled: true
  architecture: standalone
  primary:
    persistence:
      enabled: false
    extendedConfiguration: |
      log_statement = ddl
    pgHbaConfiguration: |
      local    all             all                                trust
      host     all             all        127.0.0.1/32            trust
      host     all             all        ::1/128                 trust
      host     all             all        0.0.0.0/0               md5
      host     all             all        ::/0                    md5
  auth:
    enabledPostgresUser: true
    postgresPassword: postgres
    database: document-engine
  tls:
    enabled: false

minio:
  enabled: false
redis:
  enabled: false
