apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pspdfkit-server.fullname" . }}
  labels:
    {{- include "pspdfkit-server.labels" . | nindent 4 }}
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace ( include "pspdfkit-server.fullname" . ) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKeyBase := (get $secretData "SECRET_KEY_BASE") | default ( default (randAlphaNum 256) .Values.pspdfkit.secretKeyBase | b64enc) }}
  SECRET_KEY_BASE: {{ $secretKeyBase | quote }}
