{{- if not .Values.pspdfkit.license.externalSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pspdfkit-server.fullname" . }}-license
  labels:
    {{- include "pspdfkit-server.labels" . | nindent 4 }}
data:
  ACTIVATION_KEY: {{ default "none" .Values.pspdfkit.license.activationKey | b64enc | quote }}
{{- end }}
