{{- if .Values.pspdfkit.storage.postgres.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pspdfkit-server.fullname" . }}-db-postgres
  labels:
    {{- include "pspdfkit-server.labels" . | nindent 4 }}
data:
#  PGUSER: {{ default "none" .Values.postgresql.auth.username | b64enc | quote }}
#  PGPASSWORD: {{ default "none" .Values.postgresql.auth.password | b64enc | quote }}
#
# Can't use normal user because extensions:
#
  PGUSER: {{ "postgres" | b64enc | quote }}
  PGPASSWORD: {{ default "none" .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  PGHOST: {{ printf "%s-%s" ( include "pspdfkit-server.fullname" . ) "postgresql" | b64enc | quote }}
  PGPORT: {{ default "5432" .Values.postgresql.primary.service.ports.postgresql | toString | b64enc | quote }}  
{{- if .Values.postgresql.tls.enabled }}
  PGSSL: {{ "true" | b64enc | quote }}
{{- else }}
  PGSSL: {{ "false" | b64enc | quote }}
{{- end }}
  PGDATABASE: {{ default "none" .Values.postgresql.auth.database | b64enc | quote }}
{{- end }}
