apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-assistant.fullname" . }}
  labels:
    {{- include "ai-assistant.labels" . | nindent 4 }}
data:
#
# AI Assistant configuration
#
  PORT: {{ .Values.config.port | quote }}
  FORCE_EMBEDDING_MIGRATE: {{ .Values.config.forceEmbeddingMigrate | quote }}
#
# Database
#
{{- with .Values.database }}
{{- if .enabled }}
{{-   with .postgres }}
{{-     with .host }}
  PGHOST: {{ . | quote }}
{{-     end }}
{{-     with .port }}
  PGPORT: {{ . | quote }}
{{-     end }}
{{-     with .database }}
  PGDATABASE: {{ . | quote }}
{{-     end }}
{{-     if .tls.enabled }}
  PGSSL: "true"
  PGSSL_DISABLE_VERIFY: {{ not .tls.verify | quote }}
  PGSSL_DISABLE_HOSTNAME_VERIFY: {{ not .tls.hostVerify | quote }}
{{-       with .tls.commonName }}
  PGSSL_CA_CERTS: {{ . | quote }}
{{-       end }}
{{-       if .tls.trustBundle }}
  PGSSL_CA_CERTS: {{ .tls.trustBundle | quote }}
{{-       else if .tls.trustFileName }}
  PGSSL_CA_CERT_PATH: "/certificate-stores-custom/{{ .tls.trustFileName }}"
{{-       end }}
{{-     else }}
  PGSSL: "false"
{{-     end }}
{{-   end }}
{{- end }}
{{- end }}
#
# Document Engine integration configuration
#
{{- with .Values.config.documentEngine }}
{{-   if .enabled }}
  DE_URL: {{ .url | quote }}
{{-   end }}
{{- end }}
#
# Observability
#
{{- with .Values.observability }}
  LOG_LEVEL: {{ .log.level | quote }}
  SOCKET_TRACE: {{ .log.socketTraces | quote }}
{{- end }}
#
# Can be used for hash updating
#
  HELM_CHART_VERSION: {{ include "ai-assistant.chart" . | quote }}
