{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace ( include "ai-assistant.fullname" . ) ) | default dict -}}
{{- $secretData := (get $secretObj "data") | default dict -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-assistant.fullname" . }}
  labels:
    {{- include "ai-assistant.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
data:
# License
{{- if not .Values.aiAssistantLicense.externalSecret.name }}
  {{- with .Values.aiAssistantLicense.activationKey }}
  ACTIVATION_KEY: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
# Secret key base
{{- if not (and .Values.apiAuth.externalSecret.name
                .Values.apiAuth.externalSecret.secretKeyBaseKey ) -}}
  {{- $secretKeyBase := (get $secretData "SECRET_KEY_BASE") | default ( default (randAlphaNum 256) .Values.apiAuth.secretKeyBase | b64enc) }}
  SECRET_KEY_BASE: {{ $secretKeyBase | quote }}
{{- end }}
# API auth secrets
{{- if not .Values.apiAuth.externalSecret.name }}
  API_AUTH_TOKEN: {{ default (randAlphaNum 64) .Values.apiAuth.apiToken | b64enc | quote }}
  JWT_PUBLIC_KEY: {{ default "none" .Values.apiAuth.jwt.publicKey | b64enc | quote }}
  JWT_ALGORITHM: {{ default "none" .Values.apiAuth.jwt.algorithm | b64enc | quote }}
{{- end }}
# Document Engine secrets
{{- with .Values.config.documentEngine }}
{{-   if and .enabled 
             (not .auth.externalSecret.name) }}
  DE_API_AUTH_TOKEN: {{ .auth.apiToken | b64enc | quote }}
{{-   end }}
{{- end }}
# AI service provider secrets
{{- with .Values.config.aiServiceProviderCredentials }}
{{-   with .openAI.apiKey }}
  OPENAI_API_KEY: {{ . | b64enc | quote }}
{{-   end }}
{{-   with .azureOpenAI.apiKey }}
  AZURE_API_KEY: {{ . | b64enc | quote }}
{{-   end }}
{{-   if and .awsBedrock.accessKeyId 
             .awsBedrock.secretAccessKey }}
  BEDROCK_ACCESS_KEY_ID: {{ .awsBedrock.accessKeyId  | b64enc | quote }}
  BEDROCK_SECRET_ACCESS_KEY: {{ .awsBedrock.secretAccessKey | b64enc | quote }}
{{-   end }}
{{-   with .openAICompatible.apiKey }}
  OPENAI_COMPAT_API_KEY: {{ . | b64enc | quote }}
{{-   end }}
{{- end }}
# Dashboard
{{- with .Values.dashboard.auth }}
{{-   if not .externalSecret.name }}
{{-     $dashboardUserName := (get $secretData "DASHBOARD_USERNAME") | default ( default (randAlphaNum 32) .username | b64enc) }}
{{-     $dashboardPassword := (get $secretData "DASHBOARD_PASSWORD") | default ( default (randAlphaNum 64) .password | b64enc) }}
  DASHBOARD_USERNAME: {{ $dashboardUserName | quote }}
  DASHBOARD_PASSWORD: {{ $dashboardPassword | quote }}
{{-   end }}
{{- end }}
# Can be used for hash updating
  HELM_CHART_VERSION: {{ include "ai-assistant.chart" . | b64enc | quote }}
