{{- if and .Values.database.enabled
           ( not .Values.database.postgres.externalSecretName ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-assistant.fullname" . }}-db
  labels:
    {{- include "ai-assistant.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
data:
  PGUSER: {{ .Values.database.postgres.username | b64enc | quote }}
  PGPASSWORD: {{ .Values.database.postgres.password | b64enc | quote }}
{{- end }}
