{{- if .Values.restartJob.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maestrod.fullname" . }}-restart-job
  labels:
    {{- include "maestrod.labels" . | nindent 4 }}
  {{- with .Values.restartJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
