{{- if and .Values.cloudNativePG.enabled
           .Values.cloudNativePG.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ai-assistant.storage.cloudNativePG.cluster.name" . }}
  labels:
    {{- include "ai-assistant.labels" . | nindent 4 }}
spec:
  egress:
    - {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.cloudNativePG.operatorNamespace }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.cloudNativePG.operatorReleaseName }}
      ports:
        - port: 8000
          protocol: TCP
        - port: 5432
          protocol: TCP
    - ports:
        - port: 5432
          protocol: TCP
        - port: 8000
          protocol: TCP
        - port: 9187
          protocol: TCP
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ include "ai-assistant.storage.cloudNativePG.cluster.name" . }}
      cnpg.io/podRole: instance
  policyTypes:
    - Ingress
    - Egress
{{- end }}
