image:
  repository: 111300957880.dkr.ecr.eu-west-1.amazonaws.com/maestrod

licenseSecret:
  name: ""

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: 256Mi
  limits:
    cpu: "2"
    memory: 2Gi

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/maestrod
  automount: true

deploymentAnnotations:
  reloader.stakater.com/auto: "true"

podAnnotations:
  test-pod-annotation: "yes"

podLabels:
  test-pod-label: "yes"

extraEnvs:
  - name: EXTRA_VAR
    value: extra-value

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp/extra

sidecars:
  - name: busybox-sidecar
    image: busybox:1.37
    command: ["sleep", "infinity"]

initContainers:
  - name: busybox-init
    image: busybox:1.37
    command: ["true"]

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: maestrod
