{
 "title": "<<<<DASHBOARD_TITLE>>>>",
 "tags": [ "<<<<TAGS>>>>" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "quantiles",
    "label": "Quantiles",
    "query": {
     "query": "label_values(pspdfkitd_exec{app=\"de\"},quantile)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values({app=\"de\"},pod)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({app=\"de\"},namespace)"
    }
   },
   {
    "name": "erlang_memory_detail_metrics",
    "label": "Erlang VM memory detail metrics",
    "query": { "query": "metrics(vm_memory)" }
   }
  ]
 },
 "panels": [
  {
   "title": "Erlang Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Erlang VM total memory (pod = $pod)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "vm_memory_total{pod=~\"$pod\", namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}} {pod = {{pod}} }"
      }
     ]
    },
    {
     "title": "Erlang VM memory detailed (pod = $pod) (memory_details = $erlang_memory_detail_metrics)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "repeat": "erlang_memory_detail_metrics",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "$erlang_memory_detail_metrics{pod=~\"$pod\", namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}} {pod: {{pod}}}"
      }
     ]
    },
    {
     "title": "Erlang message queue length (pod = $pod)",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "vm_messages_in_queues{pod=~\"$pod\", namespace=~\"$namespace\"}",
       "legendFormat": "{{__name__}} {pod: {{pod}}}"
      }
     ]
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "standard HTTP requests/1sec (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_server_req_end_count{group=\"standard\", pod=~\"$pod\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSPDFKit worker requests/1sec by type (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(request) (rate(pspdfkitd_exec_count{pod=~\"$pod\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "long_pool HTTP requests/1sec (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(http_server_req_end_count{group=\"long_poll\", pod=~\"$pod\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSPDFKit worker % spent on each request per 5 minute (pod = $pod)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(request) (delta(pspdfkitd_exec_sum{pod=~\"$pod\", namespace=~\"$namespace\", request!=\"checkout\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "quantile $quantiles max layer sync time (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "repeat": "quantiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(layer_sync_total{quantile=\"${quantiles:raw}\", result=\"success\", pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile $quantiles max HTTP 2xx 3xx 4xx request time (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "repeat": "quantiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(status) (http_server_req_end{quantile=\"${quantiles:raw}\", group=\"standard\", status!~\"5..\", pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile $quantiles max HTTP 5xx request time (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "repeat": "quantiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(status) (http_server_req_end{quantile=\"${quantiles:raw}\", group=\"standard\", status=~\"5..\", pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile $quantiles max HTTP 5xx request time",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 60 },
   "repeat": "quantiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(status) (http_server_req_end{quantile=\"${quantiles:raw}\", group=\"standard\", status=~\"5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile $quantiles max HTTP 5xx request time",
   "type": "timeseries",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 60 },
   "repeat": "quantiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(status) (http_server_req_end{quantile=\"${quantiles:raw}\", group=\"standard\", status=~\"5..\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSPDFKit Worker Metrics $quantiles quantile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "repeat": "quantiles"
  },
  {
   "title": "quantile $quantiles max processing time per request (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(request) (pspdfkitd_exec{app=\"de\", quantile=\"${quantiles:raw}\", pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile $quantiles max queue time PSPDFKit worker (pod = $pod)",
   "type": "timeseries",
   "description": "This represents the time spent waiting for free worker",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(pspdfkitd_queue{quantile=\"${quantiles:raw}\", pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Assets storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Quantiles $quantiles max Fetch assets storage (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "repeat": "quantiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(assets_fetch_asset{app=\"de\", quantile=\"${quantiles:raw}\", pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile $quantiles max Store asset storage time (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "repeat": "quantiles",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(assets_store_asset{app=\"de\", quantile=\"${quantiles:raw}\", pod=~\"$pod\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetches/1second (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum(rate(assets_fetch_asset_count{result=\"success\", pod=~\"$pod\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(assets_fetch_asset_count{result=\"error\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stores/1second (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "sum(rate(assets_store_asset_count{result=\"success\", pod=~\"$pod\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(assets_store_asset_count{result=\"error\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filesystem cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "FS cache (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "cache_fs_hit{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{__name__}} { pod=\"{{pod}}\"}"
    },
    {
     "expr": "cache_fs_miss{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{__name__}} { pod=\"{{pod}}\"}"
    }
   ]
  },
  {
   "title": "FS cache miss/hit ration (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cache_fs_miss{pod=~\"$pod\", namespace=~\"$namespace\"} / cache_fs_hit{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{__name__}} { pod=\"{{pod}}\"}"
    }
   ]
  },
  {
   "title": "FS cache size (pod = $pod)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cache_fs_size{pod=~\"$pod\", namespace=~\"$namespace\"}",
     "legendFormat": "{{__name__}} { pod=\"{{pod}}\"}"
    }
   ]
  }
 ]
}