apiAuth:
  apiToken: secret
  secretKeyBase: verySecretStringToNeverBeUsedInProduction

assetStorage:
  postgres:
    enabled: false

postgresql:
  enabled: false

minio:
  enabled: false

redis:
  enabled: false
