apiAuth:
  apiToken: secret
  secretKeyBase: verySecretStringToNeverBeUsedInProduction

config:
  storage:
    postgres:
      enabled: false

postgresql:
  enabled: false

minio:
  enabled: false

redis:
  enabled: false
