workloadType: StatefulSet
persistence:
  storageClassName: standard
  size: 1Gi
podManagementPolicy: Parallel

apiAuth:
  apiToken: secretThatIsNotSoSecret
  secretKeyBase: verySecretStringToNeverBeUsedInProduction
  jwt:
    enabled: true
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDcfcSsDu9Yh06oBdHqvfJVe0X0
      Jd99MadCdnsEwFDnwIxzyaZMBkGN7MyGICAky3QFb0b2wEwQSTVBvTycbI/nI/Ua
      CzUFlwrVNSuhyAjhA9pb8ig3c3z3HciCT9KsHPqqPRjmgxW4B0exCNDO0Mjckg9R
      nP8vqa0VnqmV4LdnxQIDAQAB
      -----END PUBLIC KEY-----
    algorithm: RS256

database:
  enabled: true
  migrationJob:
    enabled: false
  postgres:
    port: 5432
    username: postgres

clustering:
  enabled: true
  method: kubernetes_dns

documentLifecycle:
  expirationJob:
    enabled: true

assetStorage:
  backendType: built-in

observability:
  metrics:
    prometheusEndpoint:
      enabled: true
    grafanaDashboard:
      enabled: true

gateway:
  enabled: true
  annotations:
    test-annotation: value
  labels:
    test-label: value
  parentRefs:
    - name: my-gateway
      namespace: gateway-infra
      sectionName: https
  hostnames:
    - document-engine.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
    - matches:
        - path:
            type: PathPrefix
            value: /

cloudNativePG:
  enabled: true
