apiAuth:
  apiToken: secretThatIsNotSoSecret
  secretKeyBase: verySecretStringToNeverBeUsedInProduction
  jwt:
    enabled: true
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDcfcSsDu9Yh06oBdHqvfJVe0X0
      Jd99MadCdnsEwFDnwIxzyaZMBkGN7MyGICAky3QFb0b2wEwQSTVBvTycbI/nI/Ua
      CzUFlwrVNSuhyAjhA9pb8ig3c3z3HciCT9KsHPqqPRjmgxW4B0exCNDO0Mjckg9R
      nP8vqa0VnqmV4LdnxQIDAQAB
      -----END PUBLIC KEY-----
    algorithm: RS256

database:
  enabled: true
  migrationJob:
    enabled: false
  postgres:
    port: 5432
    username: postgres

clustering:
  enabled: true
  method: kubernetes_dns

documentLifecycle:
  cleanupJob:
    enabled: true

assetStorage:
  backendType: built-in

observability:
  metrics:
    prometheusEndpoint:
      enabled: true
    grafanaDashboard:
      enabled: true
      allNamespaces: false

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      size: 512Mi
      storageClass: standard
      accessModes:
        - ReadWriteOnce
  volumePermissions:
    enabled: true

minio:
  enabled: false

redis:
  enabled: false
