database:
  enabled: true
  migrationJob:
    enabled: false
    podAnnotations:
      do: "this"
    podLabels:
      do: "that"
  postgres:
    port: 5432
    username: postgres

assetStorage:
  backendType: s3
  backendFallback:
    enabled: true
    enabledPostgres: true
  s3:
    accessKeyId: nutrient
    secretAccessKey: despairIsUnbearable87
    bucket: whatever
    region: us-east-1
    host: minio.whatever.svc.cluster.local
    port: 80
    scheme: "http://"
  redis:
    enabled: true
    host: "127.0.0.1"
    port: 6379
    database: ""
    username: ""
    password: ""
    ttlSeconds: 3600
    useTtl: true

sidecars:
  - name: redis
    image: redis:8.2.1-alpine
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 6379
        name: redis
        protocol: TCP

observability:
  metrics:
    prometheusEndpoint:
      enabled: true

cloudNativePG:
  enabled: true
