database:
  enabled: true
  migrationJob:
    enabled: false
  postgres:
    port: 5432
    username: postgres

assetStorage:
  backendType: azure
  backendFallback:
    enabled: true
    enabledPostgres: true
  azure:
    # This is "well known" storage account for Azure Storage Emulator
    # See https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#configure-a-connection-string-for-azurite
    accountName: devstoreaccount1
    accountKey: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
    container: "document-engine-assets"
    apiUrl: "http://127.0.0.1:10000/devstoreaccount1"

# Azurite as sidecar
sidecars:
  - name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 10000
        name: blob
        protocol: TCP
  # We are using statsd-exporter to expose metrics in Prometheus format, just
  # to have a receiving endpoint
  - name: statsd-exporter
    image: prom/statsd-exporter
    imagePullPolicy: IfNotPresent
    args:
      - --statsd.listen-udp=:9125
      - --statsd.listen-tcp=:9125
      - --web.listen-address=:11254
    ports:
      - name: statsd-digested
        containerPort: 11254
        protocol: TCP

observability:
  metrics:
    statsd:
      enabled: true
      port: 9125
      host: localhost

cloudNativePG:
  enabled: true

minio:
  enabled: false

redis:
  enabled: false
