assetStorage:
  databaseMigrationJob:
    enabled: false
  assetStorageBackend: azure
  enableAssetStorageFallback: true
  enableAssetStorageFallbackPostgres: true
  postgres:
    enabled: true
    host: postgresql
    port: 5432
    username: postgres
  azure:
    # This is "well known" storage account for Azure Storage Emulator
    # See https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#configure-a-connection-string-for-azurite
    accountName: devstoreaccount1
    accountKey: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
    container: "document-engine-assets"
    apiUrl: "http://127.0.0.1:10000/devstoreaccount1"

# Azurite as sidecar
sidecars:
  - name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 10000
        name: blob
        protocol: TCP

postgresql:
  enabled: true
  fullnameOverride: postgresql
  nameOverride: postgresql
  primary:
    persistence:
      enabled: true
      size: 512Mi
      storageClass: standard
      accessModes:
        - ReadWriteOnce
  volumePermissions:
    enabled: true

minio:
  enabled: false

redis:
  enabled: false
