# Minimal test for Envoy sidecar consistent hashing
workloadType: StatefulSet
persistence:
  storageClassName: standard
  size: 5Gi
  mountPath: /data

envoySidecar:
  enabled: true

replicaCount: 2

database:
  enabled: true
  migrationJob:
    enabled: false

assetStorage:
  backendType: built-in

cloudNativePG:
  enabled: true
