pspdfkit:
  storage:
    databaseMigrationJob:
      enabled: true
    assetStorageBackend: built-in
    postgres:
      enabled: true
      host: postgresql
      port: 5432

prometheusExporter:
  enabled: true

postgresql:
  enabled: true
  fullnameOverride: postgresql
  nameOverride: postgresql
  primary:
    persistence:
      enabled: false

minio:
  enabled: false

image:
  repository: public.ecr.aws/pspdfkit/document-engine
