pspdfkit:
  storage:
    enableMigrationJobs: true
    assetStorageBackend: s3
    postgres:
      enabled: true
      host: postgresql
      port: 5432
    s3:
      accessKeyId: "pspdfkitObjectStorageRootKey"
      secretAccessKey: "pspdfkitObjectStorageRootPassword"
      bucket: "document-engine-assets"
      region: "us-east-1"
      host: "minio"
      port: 80
      scheme: "https://"

prometheusExporter:
  enabled: true

postgresql:
  enabled: true
  fullnameOverride: postgresql
  nameOverride: postgresql
  postgresqlDataDir: /ephemeral/data
  primary:
    extraVolumeMounts:
      - mountPath: /ephemeral
        name: ephemeral-data
    extraVolumes:
      - name: ephemeral-data
        emptyDir:
          sizeLimit: 1Gi
    persistence:
      enabled: false

minio:
  enabled: false
  fullnameOverride: minio
  nameOverride: minio
  auth:
    rootUser: pspdfkitObjectStorageRootKey
    rootPassword: pspdfkitObjectStorageRootPassword
  defaultBuckets: "document-engine-assets"
