name: Lint and Test Charts

# on: 
#   workflow_run:
#     workflows: [Documentation]
#     types: 
#       - completed

on: 
  pull_request:
      
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: latest

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --excluded-charts signing-service-example --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Install CloudNativePG
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add cnpg https://cloudnative-pg.github.io/charts
          helm upgrade --install cnpg \
            --namespace cnpg-system --create-namespace \
            cnpg/cloudnative-pg

      - name: Install StackGres
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add stackgres-charts https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
          helm upgrade --install stackgres-operator \
            --namespace stackgres --create-namespace \
            stackgres-charts/stackgres-operator

      - name: Install MinIO
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add minio https://operator.min.io/
          # Install operator with minimal resources
          helm upgrade --install \
            --namespace minio-operator --create-namespace \
            minio-operator minio/operator
          helm upgrade --install \
            --namespace whatever --create-namespace \
            --set tenant.name=s3thing \
            --set tenant.pools[0].name=pool-0 \
            --set tenant.pools[0].servers=1 \
            --set tenant.pools[0].volumesPerServer=1 \
            --set tenant.pools[0].size=256Mi \
            --set tenant.pools[0].storageClassName=standard \
            --set tenant.certificate.requestAutoCert=false \
            --set tenant.configSecret.accessKey=nutrient \
            --set tenant.configSecret.secretKey=despairIsUnbearable87 \
            --set tenant.buckets[0].name=whatever \
            --set tenant.buckets[0].region=us-east-1 \
            tenant minio/tenant
          sleep 30
          kubectl wait --namespace whatever --for=condition=ready pod -l v1.min.io/tenant=s3thing --timeout=300s

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add nutrient https://pspdfkit.github.io/helm-charts
          ct install --target-branch ${{ github.event.repository.default_branch }} \
                     --helm-extra-args "--timeout 240s" \
                     --helm-extra-set-args "--set=image.tag=nightly"
